# Use a distroless image as the base
FROM gcr.io/distroless/java17

# Set working directory
WORKDIR /app

# Set environment variables for Nexus and the JAR file
ARG NEXUS_URL="https://nexus.example.com/repository/maven-releases/"
ARG NEXUS_USERNAME="your_nexus_username"
ARG NEXUS_PASSWORD="your_nexus_password"
ARG GROUP_ID="com/example"
ARG ARTIFACT_ID="your-artifact-id"
ARG VERSION="1.0.0"
ARG JAR_NAME="${ARTIFACT_ID}-${VERSION}.jar"

# Download JAR from Nexus repository
RUN curl -u ${NEXUS_USERNAME}:${NEXUS_PASSWORD} -O ${NEXUS_URL}${GROUP_ID//\./\/}/${ARTIFACT_ID}/${VERSION}/${JAR_NAME}

# Expose the application port
EXPOSE 8085

# Set environment variables for the server
ENV SERVER_PORT=8085

# Run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]