# SonarQube project identification
sonar.projectKey=my-e2e-pipeline-project
sonar.projectName=my-e2e-pipeline-project
sonar.projectVersion=1.0

# Source code details
sonar.sources=src
sonar.language=java
sonar.java.binaries=target/classes

# SonarQube server details
sonar.host.url=http://13.233.90.80:9000/
sonar.token=squ_6c13ce6599f78755cc3cf22c8d470787a6864f56

# Test and coverage settings (optional)
sonar.tests=src/test
sonar.test.inclusions=**/*Test.java
sonar.exclusions=**/node_modules/**, **/*.json, **/*.yml, **/*.md

# Code coverage (if using JaCoCo for test coverage)
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml